Initial draft of p2p versions of AP data
RangerMauve/staticpub.mauve.moe pull request #2
Opened 2024-02-14 01:53 UTC by RangerMauve

- new files with p2p urls for all AP links
- Add rel=alternate to both html and AP versions of data to point at ipns
- Add ipns profile to webmention

2024-02-15 13:15 UTC, akhileshthite requested changes

2024-02-15 13:15 UTC, akhileshthite commented on newpost-ipns.jsonld
> +  "sensitive": false,
Can you make this one `true` just for testing?

2024-02-15 13:15 UTC, akhileshthite commented on newpost.jsonld
> +  "sensitive": false,
`true`

2024-02-15 13:15 UTC, akhileshthite commented on outbox-ipns.jsonld
> +	}
Mind adding these activities in here? Currently, I'm rendering them in feed, but we will have a `notification` component where we render the activities on a separate page, right?

```
    {
      "type": "Like",
      "actor": "https://staticpub.mauve.moe/about.jsonld",
      "object": "https://staticpub.mauve.moe/helloworld.jsonld"
    },
    {
      "type": "Follow",
      "actor": "https://externaluser.example.com/about.jsonld",
      "object": "https://staticpub.mauve.moe/about.jsonld"
    }

```

2024-02-15 13:15 UTC, akhileshthite commented on outbox-ipns.jsonld
> +		"actor": "https://staticpub.mauve.moe/about.jsonld",
`about-ipns`,  `followers-ipns`, `helloworld-ipfs`, `newpost-ipns`?

2024-02-15 13:15 UTC, akhileshthite commented on about.jsonld
>    "following": "https://staticpub.mauve.moe/following.jsonld",
Working on tracking [followed](https://mastodon.social/@mauve@staticpub.mauve.moe/following) accounts.
Can you follow `@dp-demo-2@dp-demo-2.sutty.nl` and `@dripline@hypha.coop` accounts and add the following.jsonld as well as following-ipns.jsonld?

2024-02-15 18:02 UTC, RangerMauve commented on outbox-ipns.jsonld
> +	}
Is notification the correct attribute? I'm not seeing it in the AP repesentation of this post for example: "https://mastodon.me.uk/users/CatherineFlick/statuses/111929349006043333/replies?min_id=111929363975865517&page=true"

2024-02-15 18:43 UTC, RangerMauve commented on about.jsonld
>    "following": "https://staticpub.mauve.moe/following.jsonld",
Hmm, I was thinking to make it possible to `GET` the followers from the social inbox instead. Mind waiting for that? https://social.distributed.press/v1/@mauve@staticpub.mauve.moe/followers

2024-02-15 19:17 UTC, akhileshthite approved these changes

2024-02-15 19:17 UTC, akhileshthite commented on outbox-ipns.jsonld
> +	}
> Is notification the correct attribute? I'm not seeing it in the AP repesentation of this post for example: "https://mastodon.me.uk/users/CatherineFlick/statuses/111929349006043333/replies?min_id=111929363975865517&page=true"

No, "notification" isn't a direct attribute or type defined in AP. We can create a separate notification component that listens for activities. This component could involve filtering activities by type (e.g., Follow, Like, Mention) and then formatting them..

2024-02-15 19:17 UTC, akhileshthite commented on about.jsonld
>    "following": "https://staticpub.mauve.moe/following.jsonld",
> Hmm, I was thinking to make it possible to `GET` the followers from the social inbox instead. Mind waiting for that? https://social.distributed.press/v1/@mauve@staticpub.mauve.moe/followers

Yep, works.

2024-02-21 02:21 UTC, merged

2024-03-11 19:22 UTC, fauno commented on .well-known/webfinger
> +      "href": "ipns://staticpub.mauve.moe/about-ipns.jsonld"
This won't work with Mastodon because it uses a Rails method to "index by" the rel attribute, so the last "self" will win. A quick hack would be to set the last rel to the HTTPS versions, with unintended consequences for non-Mastodon instances. Other options:

* Don't point the WebFinger to dweb protocols (!)
* Don't use rel=self for dweb protocols

2024-03-11 19:23 UTC, fauno commented on .well-known/webfinger
> +      "href": "ipns://staticpub.mauve.moe/about-ipns.jsonld"
The object produced by the indexation:

```json
{
  "self": {
    "rel": "self",
    "type": "application/activity+json",
    "href": "ipns://skel.sutty.local/about.jsonld"
  },
  "http://webfinger.net/rel/profile-page": {
    "rel": "http://webfinger.net/rel/profile-page",
    "type": "text/html",
    "href": "https://skel.sutty.local"
  }
}
```

2024-03-11 19:24 UTC, fauno commented on .well-known/webfinger
> +      "href": "ipns://staticpub.mauve.moe/about-ipns.jsonld"
The webfinger object:

```json
{
  "subject": "acct:skel@skel.sutty.local",
  "links": [
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://skel.sutty.local/about.jsonld"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "ipns://skel.sutty.local/about.jsonld"
    },
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://skel.sutty.local"
    }
  ]
}
```

2024-03-11 19:24 UTC, fauno commented on .well-known/webfinger
> +      "href": "ipns://staticpub.mauve.moe/about-ipns.jsonld"
Third option: Use rel=alternate

2024-03-11 19:37 UTC, RangerMauve commented on .well-known/webfinger
> +      "href": "ipns://staticpub.mauve.moe/about-ipns.jsonld"
Hmm, that's unfortunate that mastodon uses the last instead of first.